CREATE TABLE IF NOT EXISTS users
(
    USER_ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    NAME    VARCHAR(140)                                        NOT NULL,
    EMAIL   VARCHAR(140) UNIQUE                                 NOT NULL

);

CREATE TABLE IF NOT EXISTS requests
(
    REQUEST_ID   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    DESCRIPTION  VARCHAR(400)                                        NOT NULL,
    REQUESTER_ID BIGINT,
    CREATED      TIMESTAMP                                           NOT NULL
);

CREATE TABLE IF NOT EXISTS items
(
    ITEM_ID      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    NAME         VARCHAR(140)                                        NOT NULL,
    DESCRIPTION  VARCHAR(400)                                        NOT NULL,
    IS_AVAILABLE BOOLEAN DEFAULT true,
    OWNER_ID     BIGINT,
    REQUEST_ID   BIGINT
);

CREATE TABLE IF NOT EXISTS bookings
(
    BOOKING_ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    START_DATE TIMESTAMP                                           NOT NULL,
    END_DATE   TIMESTAMP                                           NOT NULL,
    ITEM_ID    BIGINT,
    BOOKER_ID  BIGINT,
    STATUS     VARCHAR
);

CREATE TABLE IF NOT EXISTS comments
(
    COMMENT_ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    TEXT       VARCHAR(400)                                        NOT NULL,
    ITEM_ID    BIGINT,
    AUTHOR_ID  BIGINT,
    CREATED    TIMESTAMP                                           NOT NULL
);

